# Generated by Django 4.0.6 on 2022-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('page_num', models.IntegerField()),
                ('an_of_rot', models.IntegerField()),
                ('edited_file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
